#pragma once

enum NetworkPacketToServer
{
	PACKET_TO_SERVER_INFO_REQUEST,

	PACKET_TO_SERVER_CONNECT_REQUEST,
	PACKET_TO_SERVER_DISCONNECT,

	PACKET_TO_SERVER_PONG,
};

enum NetworkPacketToClient
{
	PACKET_TO_CLIENT_INFO_RESPONSE,

	PACKET_TO_CLIENT_CONNECT_RESPONSE,
	PACKET_TO_CLIENT_DISCONNECT,

	PACKET_TO_CLIENT_PING,
};